### PR TITLE
simplified introduction, einstein

### PR DESCRIPTION
**Pull request by markedwardmurray**
https://github.com/learn-co-curriculum/reading-ios-looping-and-conditionals/issues/5

### CODE REVIEW

**Comment by jmburges** [comment]
:sparkling_heart: LOVE IT  :sparkling_heart: 

:shipit:

**Comment by markedwardmurray** [comment]
sparkly hearts! wow

**Comment by jmburges** [comment]
yeah sparkle hearts! took a small poke from me and made way better, and mark-ified it :). love it

**Comment by markedwardmurray** [comment]
:sunglasses:

**Pull request merged**
